steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --port=8080
      - --no-allow-unauthenticated
images:
  - ${_IMAGE}
substitutions:
  _SERVICE: traficcagent
  _REGION: southamerica-east1
  _IMAGE: southamerica-east1-docker.pkg.dev/$PROJECT_ID/traficcagent/traficcagent:$COMMIT_SHA

